# Change these first
owner: ksemkav
repo: segerlab-status

sites:
  - name: Segerlab
    url: https://segerlab.ru/
  - name: Segerlab Logs
    url: https://log.segerlab.ru/
  - name: Segerlab DEV
    url: https://dev.segerlab.ru/

status-website:
  baseUrl: /segerlab-status
  logoUrl: https://segerlab.ru/apple-touch-icon.png
  name: Segerlab Upptime
  navbar:
    - title: Status
      href: /
